---
- name: Perform prerequisite setup
  ansible.builtin.include_tasks: prereq.yml

- name: Set up Kubernetes control plane
  ansible.builtin.include_tasks: control-plane.yml
  when: inventory_hostname in groups['kubernetes_control_plane']

- name: Set up Kubernetes worker nodes
  ansible.builtin.include_tasks: worker-node.yml
  when: inventory_hostname in groups['kubernetes_worker_nodes']
