---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Perform prerequisite setup
  ansible.builtin.include_tasks: prereq.yml

- name: Set up High Availability components
  ansible.builtin.include_tasks: ha.yml
  when: k8s_ha_enabled

# - name: Set up Kubernetes control plane
#   ansible.builtin.include_tasks: control-plane.yml
#   when: inventory_hostname in groups['k8s_control_plane']

# - name: Set up Kubernetes worker nodes
#   ansible.builtin.include_tasks: worker-node.yml
#   when: inventory_hostname in groups['k8s_worker_nodes']
