---
- name: Install prerequisites (Debian)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - procps
    state: present

- name: Add Kubernetes apt repository key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present
    update_cache: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - "kubelet={{ kubernetes_version }}.{{ kubernetes_version_minor }}-*"
      - "kubeadm={{ kubernetes_version }}.{{ kubernetes_version_minor }}-*"
      - "kubectl={{ kubernetes_version }}.{{ kubernetes_version_minor }}-*"
    state: present
    update_cache: true
    allow_downgrade: true
  notify: Restart kubelet

- name: Let iptables see bridged traffic
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
