---
- name: Check if node is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubernetes_kubelet_conf

- name: Join worker node to cluster
  ansible.builtin.command: "{{ hostvars[groups['kubernetes_control_plane'][0]].kubernetes_join_command_worker }}"
  when: not kubernetes_kubelet_conf.stat.exists
