---
- name: Check if node is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_kubelet_conf

- name: Join worker node to cluster
  ansible.builtin.command: "{{ hostvars[groups['k8s_control_plane'][0]].k8s_join_command_worker }}"
  when: not k8s_kubelet_conf.stat.exists
